%YAML:1.0
date: "Sun Aug 26 21:19:53 2012\n"
# gui dimension
width: 1280
height: 720
# image thumbnail on gui 
thumb_width: 64
thumb_height: 48
# the image used within the pipeline
im_width: 640
im_height: 480
#
out_width: 800
out_height: 600
